### ISSUE TITLE
skype

### ISSUE THREAD

**Issue by scorp12** [v1ctoralex/SPITFIRE#1]
if you can are are willing contact me on skype or send me messenger you use, ive been following daizee for serveral years now. maybe we together can figure out how to make this a full thing. ive had several versions setup using wamp and xampp, currently trying to get in contact with the creator to see if any progress has been made recently.

skype is stingerisback@hotmail.com

**Comment by v1ctoralex** [comment]
Thank you for your reply Scorp, right now I dont really have that much time to work on this project, unfortunatly I think Daizee has abandoned this project but I managed to compile and run everything he has   posted. I will also create a yotube video where I will explain everything. When I will have more time to work on this I will contact you.

**Comment by scorp12** [comment]
at the moment daizee has had some other things to take care of setting this on the back burner.  i have compiled spitfire1, currently working to figure out spitfireII and spitfireIII. im not knowledgable in coding but trying to learn currently. i was able to get a program that collects some info about evony packets to help with building the server up. i was also given an unreleased build of spitfire that i can not give out. i have no source files for it, but it allows you to march out troops just nothing else with them.

**Comment by v1ctoralex** [comment]
The main problem with this project is that I dont really know the exact versions of the dependencies, it takes a lot of time to find out,recompile every library, etc. I would suggest to rewrite everything from scratch but this also takes a lot of time and a lot of knowledge about c++ and the libraries Daizee used. Unfortunetly my time is quite limited right now. Even if I had time, my knowledge regarding packet capturing is quite limited too. All I can say for now is that I will come back to this project in this future.

**Comment by scorp12** [comment]
As ive sid i have alot of info from playing with this aswell has from the developer. I can do all the research to help out while i learn sone coding

**Comment by scorp12** [comment]
![2017-01-15 18_01_34-shellview](https://cloud.githubusercontent.com/assets/6216835/21967014/b6682312-db4c-11e6-885e-4384ccd47526.png)

here is a sample of the packet names used by evony

**Comment by scorp12** [comment]
within the folders is info from both the client and server that can up in the structure of the system

**Comment by v1ctoralex** [comment]
This looks quite nice to be honest, What software did you use to get this ? I managed to decompile the whole server client but I didnt look into it that much

**Comment by scorp12** [comment]
Its was written by the creator of spitfire.

**Comment by v1ctoralex** [comment]
I dont think so, there must be something, some kind of network sniffer. For example when you click "login" button on the web client, some packets are sent somewhere that is unreachable because there was no server in the first place. Based on these packets Daizee was able to develop step by step the server sided functions.

**Comment by scorp12** [comment]
It was a seperate profram she created that was able to intercept the packets between the client and server while playing the game. It was written so that all data was saved in exact name. Type and value of the data already readable to the person. Ill post a pic of tge data from client and server in a few to show u what i mean

**Comment by v1ctoralex** [comment]
Even if this is true, these packets are not encrypted so there must be a easier way to intercept them.

**Comment by scorp12** [comment]
![2017-01-15 18_27_21-skype issue 1 v1ctoralex_spitfire](https://cloud.githubusercontent.com/assets/6216835/21967207/7ae1a0ee-db50-11e6-96eb-efdd2b596c74.png)
![2017-01-15 18_27_39-field getotherfieldinfo](https://cloud.githubusercontent.com/assets/6216835/21967205/7aded1ca-db50-11e6-9ccf-ef7daa2735bf.png)
![2017-01-15 18_28_02-258491321 client txt - notepad](https://cloud.githubusercontent.com/assets/6216835/21967206/7ae192fc-db50-11e6-9ddc-62f55ad65512.png)

**Comment by v1ctoralex** [comment]
Ok this looks great, if you want you can mail me with this and I can look more into it, I will also decompile againt the client and see if I get more info from that.

**Comment by scorp12** [comment]
what are you using to decompile the client

**Comment by v1ctoralex** [comment]
Flash Decompiler Trillix

**Comment by scorp12** [comment]
oh ok

**Comment by scorp12** [comment]
having to put the file on google drive, ill email you the link when its done

**Comment by scorp12** [comment]
what do you use for an ide compiler

**Comment by v1ctoralex** [comment]
Adobe Flash Studio, but as I said before, I didnt looked that much into it so I didnt manage to recompile it.

**Comment by scorp12** [comment]
sorry i meant for writing c++

**Comment by v1ctoralex** [comment]
Visual Studio 2012, if I try to use anything else(VS2013,2015 etc) I will have compatibily issues with VC++ Libraries and I didnt want that to happen because there were already a lot of compatibility issues regarding 
dependencies versions.

**Comment by scorp12** [comment]
so far the only one i havent find the version for was POCO c++, but for boost she used 1.57, Lua was 5.2

**Comment by scorp12** [comment]
gmail wont let me send a rar file so i have to download google drive and then upload the file, google servers are running slow for me tonight

**Comment by v1ctoralex** [comment]
Even if you are going to find the exact version of every library, you'll need to recompile every one of them before being actualy able to compile the whole project. As I said, when I will have more time I will use fiddler to intercept the packets and then maybe I will be able to write from scratch the server sided part using c# or c++.  It takes a lot of time and you need a lot of knowledge regarding programming, knowledge you cannot aquire in days or few weeks. With that being said I have to go now, if I find anything that could help you I will mail you. Thank you for your time.

**Comment by scorp12** [comment]
I have compiled  this project hundreds of times. Im confident i will find the proper setup for compiling all cersions of it from diazee
